import React from "react";
import { RJSFSchema } from "@rjsf/utils";
import { BaseQuestionApp } from "@concord-consortium/question-interactives-helpers/src/components/base-question-app";
import { IAuthoredState, IInteractiveState } from "./types";
import { Runtime } from "./runtime";

const baseAuthoringProps = {
  schema: {
    type: "object",
    properties: {
      version: {
        type: "number",
        default: 1
      },
      questionType: {
        type: "string",
        default: "iframe_interactive"
      },
      prompt: {
        title: "Prompt",
        type: "string"
      },
      buttonLabel: {
        title: "Button Label (limit: 30 characters)",
        type: "string",
        maxLength: 30
      },
      scriptUrl: {
        title: "Script URL",
        type: "string",
        format: "uri"
      }
    }
  } as RJSFSchema,

  uiSchema: {
    "ui:order": [
      "prompt",
      "buttonLabel",
      "scriptUrl",
      "*"
    ],
    version: {
      "ui:widget": "hidden"
    },
    questionType: {
      "ui:widget": "hidden"
    },
    prompt: {
      "ui:widget": "richtext",
      "ui:help": "Example: \"Click this button when you have finished answering all the questions.\""
    },
    buttonLabel: {
      "ui:placeholder": "Example: \"I'm Done!\""
    },
    scriptUrl: {
      "ui:widget": "textarea",
      "ui:options": {
        "rows": 6
      },
      "ui:placeholder": "Example: \"https://example.com/action-script\"",
      "ui:help": "Paste the URL to the action script for this button to run when clicked. Scripts are generated by a developer."
    }
  }
};

const isAnswered = (interactiveState: IInteractiveState | null) => {
  return true;
};

export const App = () => (
  <BaseQuestionApp<IAuthoredState, IInteractiveState>
    Runtime={Runtime}
    baseAuthoringProps={baseAuthoringProps}
    isAnswered={isAnswered}
  />
);
